=== Luis318/GRUPO03_PARCIAL1/GRUPO03_PARCIAL1/Parcial1-Parte3/parcial1_3grupo03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="Parcial1_3">
      <xs:complexType>
        <xs:sequence>
          <xs:element  ref="registro" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
    
      <xs:element name="registro">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="periodo" type="xs:string"/>
          <xs:element  ref="factura" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute  name="numero" type="xs:positiveInteger" use="required"/>
        <xs:attribute  name="responsable" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:element>

    <xs:element name="factura">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="fechaEmision" type="xs:date"/>
          <xs:element ref="cliente" minOccurs="1"/>
          <xs:element ref="direccion" minOccurs="0"/>
          <xs:element ref="lineafactura" minOccurs="1"/>
          <xs:element ref="IVA" minOccurs="0"/>
          <xs:element name="total" type="precio"/>
        </xs:sequence>
        <xs:attribute name="num" type="xs:integer" use="required"/>
        <xs:attribute name="tipo" type="tipofactura" use="required"/>
      </xs:complexType>
    </xs:element>
     
    <xs:element name="cliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element  name="nombre" type="xs:string" />
        <xs:element  ref="documento" />    
        <xs:element name="telefono" type="tipotelfs" minOccurs="0"/>
        <xs:element name="email" type="tipoemail"/>
      </xs:sequence>
      <xs:attribute name="cod" type="xs:integer" use="required"/>
      <xs:attribute name="sexo" type="tiposexo"/>
    <xs:attribute name="estadoCivil" type="estadocivil"/>
    </xs:complexType>
    </xs:element> 

    <xs:simpleType name="precio">
      <xs:restriction base="xs:decimal">
        <xs:totalDigits value="9"/>
        <xs:fractionDigits value="2"/>
        <xs:minExclusive value="0"/>
      </xs:restriction>
     </xs:simpleType>
    
    <xs:simpleType name="tipofactura">
      <xs:restriction base="xs:string">
      <xs:pattern value="final|credito"/>
      </xs:restriction>
    </xs:simpleType>
      
    <xs:element name="documento">
      <xs:complexType>
        <xs:choice>
          <xs:element  ref="dui" />
          <xs:element ref="pasaporte"/>
        </xs:choice>
      </xs:complexType>
    </xs:element>
    
     <xs:element name="dui">
        <xs:complexType>
        <xs:simpleContent>
          <xs:extension base="tipoDUI">
          <xs:attribute name="vence" type="xs:date" use="required"/>
          </xs:extension>
        </xs:simpleContent>
        </xs:complexType>  
      </xs:element>
    
    <xs:simpleType name="tipoDUI">
        <xs:restriction base="xs:token">
        <xs:pattern value="[0-9]{7,8}-[0-9]{1}"/>
        </xs:restriction>
    </xs:simpleType>
      
      <xs:element name="pasaporte">
        <xs:complexType>
        <xs:simpleContent>
          <xs:extension base="tipoPasaporte">
          <xs:attribute name="pais" type="tipoPais" use="required"/>
          </xs:extension>
        </xs:simpleContent>
        </xs:complexType>  
      </xs:element>
      
        <xs:simpleType name="tipoPasaporte">
        <xs:restriction base="xs:token">
        <xs:pattern value="[A-Z]{1}[0-9]{8}"/>
        </xs:restriction>
      </xs:simpleType>
      
       <xs:simpleType name="tipoPais">
        <xs:restriction base="xs:token">
        <xs:pattern value="[A-Z]{3}"/>
        </xs:restriction>
      </xs:simpleType>
      
      
      <xs:complexType name="tipotelfs">
        <xs:sequence>
        <xs:group ref="grupotelfs"/>
        </xs:sequence>
      </xs:complexType>

  <xs:group name="grupotelfs">
          <xs:sequence>
          <xs:element name="fijo">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
            <xs:pattern value="2[0-9]{7}"/>
            </xs:restriction>
            </xs:simpleType>
            </xs:element>
          <xs:element name="celular">
            <xs:complexType >
            <xs:simpleContent>
            <xs:extension base="tipocel">
            <xs:attribute name="compania" type="tipocia" use="required"/>
            </xs:extension>
            </xs:simpleContent>
            </xs:complexType>
          </xs:element>
          </xs:sequence>
      </xs:group>
  <xs:element name="celular">
  <xs:complexType>
        <xs:simpleContent>
          <xs:extension base="tipocel">
          <xs:attribute name="compania" type="tipocia" use="required"/>
          </xs:extension>
        </xs:simpleContent>
        </xs:complexType>  
  </xs:element>

    <xs:simpleType name="tipocel">
      <xs:restriction base="xs:integer">
      <xs:pattern value="[6-7][0-9]{7}"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tipocia">
      <xs:restriction base="xs:string">
      <xs:pattern value="tigo|Movistar|Claro|Digicel|Otro"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="estadocivil" >
      <xs:restriction base="xs:string">
      <xs:enumeration value="Soltero" />
      <xs:enumeration value="Casado" />
      <xs:enumeration value="Divorsiado" />
	    <xs:enumeration value="Viudo" />
      <xs:enumeration value="Soltera" />
      <xs:enumeration value="Casada" />
      <xs:enumeration value="Divorsiada" />
	    <xs:enumeration value="Viuda" />
      </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="direccion">
      <xs:complexType>
      <xs:sequence>
          <xs:choice>
          <xs:element name="casa" type="xs:string"/>
              <xs:element name="oficina" type="xs:string"/>
          </xs:choice>
          <xs:element name="municipio" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="depto" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:element>

    <xs:element name="codigo">
        <xs:complexType>
        <xs:simpleContent>
          <xs:extension base="xs:positiveInteger">
          <xs:attribute name="tipo" type="xs:string" use="required"/>
          </xs:extension>
        </xs:simpleContent>
        </xs:complexType>  
       </xs:element>
    
    <xs:element name="lineafactura">
      <xs:complexType>
      <xs:sequence>
        <xs:element ref="codigo"/>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="cantidad" type="xs:positiveInteger" minOccurs="1"/>
        <xs:element name="precio" type="precio"/>
        <xs:element name="subtotal" type="precio"/>
      </xs:sequence>
      <xs:attribute name="factura" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="moneda" type="xs:string" />
      </xs:complexType>
    </xs:element>
   
   <xs:element name="IVA">
   <xs:complexType>
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
      <xs:attribute name="valor" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
    </xs:complexType>  
   </xs:element>
    
    <xs:simpleType name="tiposexo" >
      <xs:restriction base="xs:string">
      <xs:enumeration value="Masculino" />
      <xs:enumeration value="Femenino" />
	  <xs:enumeration value="Prefiero no decirlo" />
      </xs:restriction>
    </xs:simpleType>
	
    <xs:simpleType name="tipoemail" >
        <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z0-9_\.\'\-]{4,30}@.+\..{3,5}"/>
        </xs:restriction>
      </xs:simpleType>
		
</xs:schema>

=== Luis318/GRUPO03_PARCIAL1/GRUPO03_PARCIAL1/Parcial1-Parte3/registro_facturas_grupo03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- grupo 03  -->
<Parcial1_3  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="parcial1_3grupo03.xsd">
  <registro numero="1234" responsable="Lic. Inocencio Perez">
    <periodo>Marzo 2013</periodo>
    <factura  num="564" tipo="final" >
      <fechaEmision>2013-03-11</fechaEmision>
      <cliente cod="223" sexo="Femenino" estadoCivil="Casada">
        <nombre>Maria Velez</nombre>
        <documento>
          <dui vence="2018-03-03">02349867-9</dui>
        </documento>
        <telefono>
          <fijo>24356789</fijo>
           <celular compania="tigo">78523164</celular>
        </telefono>
       <email>mariav@gmail.com</email>
      </cliente>
     <direccion depto="San Salvador">
    <casa>Prados del Bosque Num.23</casa>
    <municipio>San Salvador</municipio>
    </direccion>
      <lineafactura  factura="564" moneda="$">
     <codigo tipo="souvenir">498</codigo>
      <descripcion>Llavero estampas de mi pueblo: Izalco</descripcion>
      <cantidad>10</cantidad>
      <precio>20</precio>
      <subtotal>200</subtotal>
      </lineafactura>
      <IVA valor="13%">26</IVA>
      <total>226.00</total>
    </factura>
    
    <factura num="345" tipo="credito">
    <fechaEmision>2013-10-03</fechaEmision>
    <cliente cod="5032" sexo="Femenino" estadoCivil="Soltera">
    <nombre>Julia Perez</nombre>
    <documento>
      <pasaporte pais="USA">A98672340</pasaporte>
    </documento>
    <telefono>
        <fijo>25456987</fijo>
        <celular compania="tigo">79754612</celular>
    </telefono>
    <email>jperez@sica.com</email>
    </cliente>
    <direccion depto="La libertad">
    <oficina>5 Av. Sur</oficina>
    <municipio>Antiguo Cuscatlán</municipio>
    </direccion>
     <lineafactura factura="570" moneda="$">
      <codigo tipo="pcportatiles">734</codigo>
      <descripcion>netbook acer a240</descripcion>
      <cantidad>3</cantidad>
      <precio> 350.00</precio>
      <subtotal>1050.00</subtotal>
     </lineafactura>
      <IVA valor="13%">136.5</IVA>
      <total>1186.50</total>
    </factura>
    
    <factura num="575" tipo="credito">
    <fechaEmision>2020-03-23</fechaEmision>
    <cliente cod="5327" sexo="Masculino" estadoCivil="Viudo">
      <nombre>Jhon Witch</nombre>
      <documento>
        <pasaporte pais="USA">A98670234</pasaporte>
      </documento>
      <telefono>
      <fijo>21451978</fijo>
      <celular compania="Movistar">78923546</celular>
      </telefono>
      <email>jwitch@usaid.com</email>
    </cliente>
    <direccion depto="La Libertad">
      <oficina>Final 25 Av. Norte</oficina>
      <municipio>Santa Tecla</municipio>
    </direccion>
    <lineafactura factura="575" moneda="$">
      <codigo tipo="accesorio_pc">247</codigo>
      <descripcion>Mouse inalámbrico</descripcion>
      <cantidad>5</cantidad>
      <precio>10.00</precio>
      <subtotal>50.00</subtotal>
    </lineafactura>
    <IVA valor="13%">6.50</IVA> 
    <total>56.50</total>
  </factura>
  
    <factura num="590" tipo="final">
   <fechaEmision>2020-03-26</fechaEmision>
    <cliente cod="617" sexo="Masculino" estadoCivil="Casado">
      <nombre>Juan Pérez</nombre>
      <documento>
        <pasaporte pais="SLV">A40298367</pasaporte>
      </documento>
      <telefono>
        <fijo>28459603</fijo>
       <celular compania="Claro">76023546</celular>
       </telefono>
      <email>jperez@gmail.com</email>
    </cliente>
    <direccion depto=""><casa></casa><municipio></municipio></direccion>
    <lineafactura factura="590" moneda="$">
      <codigo tipo="perecedero">213</codigo>
      <descripcion>Agua embotellada</descripcion>
      <cantidad>10</cantidad>
      <precio>0.50</precio>
      <subtotal>5.00</subtotal>
    </lineafactura>
    <IVA valor="13%">0.65</IVA>
    <total>5.65</total>
  </factura>
  
    <factura num="593" tipo="final">
    <fechaEmision>2020-03-30</fechaEmision>
    <cliente cod="177" sexo="Masculino" estadoCivil="Soltero">
      <nombre>Pedro Portillo</nombre>
      <documento>
        <pasaporte pais="SLV">A43698027</pasaporte>
      </documento>
      <telefono>
        <fijo>25267894</fijo>
        <celular compania="Claro">76028642</celular>
      </telefono>
      <email>pportillo@hotmail.com</email>
    </cliente>
    <lineafactura factura="593">
      <codigo tipo="perecedero">215</codigo>
      <descripcion>Soda enlatada</descripcion>
      <cantidad>24</cantidad>
      <precio>0.50</precio>
      <subtotal>12.00</subtotal>
    </lineafactura>
    <IVA valor="13%">1.56</IVA>
    <total>13.56</total>
  </factura>
  
    <factura num="585" tipo="credito">
    <fechaEmision>2013-03-29</fechaEmision>
    <cliente cod="5327" sexo="Masculino" estadoCivil="Casado">
      <nombre>Jhon Smith</nombre>
      <documento>
        <dui vence="2018-06-03">02810867-0</dui>
      </documento>
      <telefono>
      <fijo>21203674</fijo>
      <celular compania="tigo">78923546</celular>
      </telefono>
      <email>jsmith@usaid.com</email>
    </cliente>
    <direccion depto="La Libertad">
      <oficina>Final 25 Av. Norte</oficina>
      <municipio>Santa Tecla</municipio>
    </direccion>
    <lineafactura factura="575" moneda="$">
      <codigo tipo="accesorio_pc">247</codigo>
      <descripcion>Mouse inalámbrico</descripcion>
      <cantidad>10</cantidad>
      <precio>10.00</precio>
      <subtotal>100.00</subtotal>
    </lineafactura>
    <IVA valor="13%">13.00</IVA>
    <total>113.00</total>
   </factura>
    
   
    <factura num="588" tipo="final">
   <fechaEmision>2020-04-17</fechaEmision>
    <cliente cod="2362" sexo="Masculino" estadoCivil="Viudo">
      <nombre>Roberto López</nombre>
      <documento>
        <pasaporte pais="SLV">A24278905</pasaporte>
      </documento>
      <telefono>
        <fijo>24106398</fijo>
       <celular compania="Claro">72779648</celular>
       </telefono>
      <email>roblopez@gmail.com</email>
    </cliente>
    <direccion depto=""><casa></casa><municipio></municipio></direccion>
    <lineafactura factura="588" moneda="$">
      <codigo tipo="perecedero">213</codigo>
      <descripcion>Cartón de Leche</descripcion>
      <cantidad>3</cantidad>
      <precio>1.30</precio>
      <subtotal>3.90</subtotal>
    </lineafactura>
    <IVA valor="13%">0.51</IVA>
    <total>4.41</total>
  </factura>
  
    <factura num="453" tipo="final">
    <fechaEmision>2020-05-30</fechaEmision>
    <cliente cod="424" sexo="Femenino" estadoCivil="Soltera">
      <nombre>Laura Rodríguez</nombre>
      <documento>
        <pasaporte pais="SLV">A47830596</pasaporte>
      </documento>
      <telefono>
        <fijo>26781056</fijo>
        <celular compania="tigo">78869460</celular>
      </telefono>
      <email>lrodriguez@hotmail.com</email>
    </cliente>
    <lineafactura factura="453">
      <codigo tipo="perecedero">345</codigo>
      <descripcion>Refresco enlatado</descripcion>
      <cantidad>10</cantidad>
      <precio>0.50</precio>
      <subtotal>5.00</subtotal>
    </lineafactura>
    <IVA valor="13%">0.65</IVA>
    <total>5.65</total>
  </factura>
  
    <factura num="840" tipo="credito">
    <fechaEmision>2014-08-05</fechaEmision>
    <cliente cod="2057" sexo="Femenino" estadoCivil="Viuda">
    <nombre>Susana Rivas</nombre>
    <documento>
      <pasaporte pais="USA">A98672340</pasaporte>
    </documento>
    <telefono>
    <fijo>20136974</fijo>
    <celular compania="Claro">76543505</celular>
    </telefono>
    <email>srivas@sica.com</email>
    </cliente>
    <direccion depto="San Salvador">
    <oficina>12 Av. Norte</oficina>
    <municipio>San Salvador</municipio>
    </direccion>
     <lineafactura factura="840" moneda="$">
      <codigo tipo="pcportatiles">544</codigo>
      <descripcion>laptop HP 14</descripcion>
      <cantidad>1</cantidad>
      <precio> 459.00</precio>
      <subtotal>459.00</subtotal>
     </lineafactura>
      <IVA valor="13%">59.67</IVA>
      <total>518.67</total>
    </factura>
    
    <factura num="799" tipo="credito">
    <fechaEmision>2019-10-15</fechaEmision>
    <cliente cod="2599" sexo="Masculino" estadoCivil="Casado">
      <nombre>Jason Clinton</nombre>
      <documento>
        <pasaporte pais="USA">A20808795</pasaporte>
      </documento>
      <telefono>
      <fijo>24156398</fijo>
      <celular compania="Digicel">78547385</celular>
      </telefono>
      <email>jclinton@usaid.com</email>
    </cliente>
    <direccion depto="La Paz">
      <oficina>4 Av. Norte</oficina>
      <municipio>Zacatecoluca</municipio>
    </direccion>
    <lineafactura factura="799" moneda="$">
      <codigo tipo="accesorio_pc">329</codigo>
      <descripcion>Audifono Hyper</descripcion>
      <cantidad>4</cantidad>
      <precio>80.00</precio>
      <subtotal>320.00</subtotal>
    </lineafactura>
    <IVA valor="13%">41.60</IVA> 
    <total>361.60</total>
  </factura>
   
  </registro>
</Parcial1_3>
